config/routes.rb
Byus::Application.routes.draw do

  match "/stats", to: 'stats#index'

  resources :bins, only: [:create, :update, :new, :edit] do
    match "", to: 'links#index', via: :get
    resources :links, only: [:create, :destroy, :index]
  end

  namespace :public do
    resources :bins, only: [] do
      match "", to: 'links#index', via: :get
      resources :links, only: :index
    end
  end

  match '/links/latest', controller: :links, action: :latest, via: :get

  match "b/:bin_id", to: "links#bookmarklet", as: 'bookmarklet'

  # Simple heartbeat check. Don't waste resources
  match 'heartbeat', to: proc { [200, {}, ''.chars] }

  root to: 'bins#new'
end

app/models/bin.rb
require 'digest/sha1'
class Bin < ActiveRecord::Base
  has_many :links, order: 'links.updated_at DESC', inverse_of: :bin

  attr_accessible :title, :links_attributes, :allow_public
  accepts_nested_attributes_for :links

  validates_presence_of :secret_hash, :public_hash, :title

  before_validation :generate_hash, unless: :secret_hash
  before_validation :generate_title

  def to_param
    secret_hash
  end

  def public_status
    allow_public? ? 'public' : 'private'
  end

  private

  def generate_hash
    hash = Digest::SHA1.hexdigest("#{title}--#{Time.now}")
    self.secret_hash ||= id.to_i.to_s(16) + hash.slice(4..12)
    self.public_hash ||= hash.slice(12..18) + id.to_i.to_s(18)
  end

  def generate_title
    self.title ||= links.first.try(:location)
  end
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :links

  scope :top,  order("links_count DESC").limit(5)
end

app/models/link.rb
class Link < ActiveRecord::Base
  TIME_RANGES = %w(24 48 168)
  DEFAULT_TIME_RANGE = "24"
  belongs_to :bin
  belongs_to :domain, counter_cache: true

  validates_presence_of :bin, :location, :title, :domain
  validates_format_of :location , with: URI::regexp,
    message: "should be like http://example.com/"
  validates_uniqueness_of :location, scope: :bin_id

  before_validation :normalize_location, :assign_title, :assign_domain

  scope(:from_hours_ago,
        ->(hours) {where("updated_at >= ?",Link.viewing_range(hours).to_i.hours.ago)})
  scope :nonprivate, joins(:bin).where(bins: {allow_public: true})
  scope :latest, order("#{table_name}.created_at DESC").limit(30)

  def self.since(time)
    parsedTime = time ? Time.zone.parse(time).to_s(:db) : 24.hours.ago
    where("updated_at > ?", parsedTime).order('updated_at DESC')
  end

  def secret_hash
    bin.secret_hash
  end

  def self.normalize_url(url)
    return if url.blank?
    begin
      URI.parse(url).normalize.to_s
    rescue URI::InvalidURIError
      url
    end
  end

  def self.viewing_range(time)
    TIME_RANGES.include?(time) ? time : DEFAULT_TIME_RANGE
  end

  def display_title
    title || location
  end

  private

  def normalize_location
    self.location = Link.normalize_url(location)
  end

  def assign_title
    self.title ||= location
  end

  def assign_domain
    begin
      self.domain = Domain.find_or_create_by_root(URI.parse(self.location).host)
    rescue
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :ensure_domain

  APP_DOMAIN = 'this.isby.us'

  def ensure_domain
    return unless ::Rails.env.production?
    if request.env['HTTP_HOST'] != APP_DOMAIN
      redirect_to "http://#{APP_DOMAIN}#{request.env['PATH_INFO']}", status: 301
    end
  end

  def title
    ""
  end
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  expose(:bin) { Bin.find_by_secret_hash(params[:id]) || Bin.new(params[:bin]) }

  def create
    unless bin.links.first.valid?
      bin.title = bin.links.first.location
      bin.links.clear
    end
    if bin.save
      redirect_to bin_links_path(bin)
    else
      flash.now[:error] = "Unable to create a new bin"
      render 'new'
    end
  end

  def update
    if bin.update_attributes(params[:bin])
      flash[:success] = "Bin Updated: "
      flash[:success] << "Updated name!" if params[:bin][:title]
      flash[:success] << "Bin is now #{ bin.public_status }" if params[:bin][:allow_public]
    else
      flash[:error] = "Unable to update bin"
    end
    redirect_to bin_links_path(bin)
  end

  def title
    "Make a Bin"
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  expose(:bin) { Bin.find_by_secret_hash params[:bin_id] }
  expose(:link) do
    if params[:link]
      link = Link.normalize_url(params[:link][:location])
      bin.links.find_by_location(link) ||
        bin.links.build(params[:link])
    else
      bin.links.build
    end
  end
  expose(:links) do
    if params[:time]
      bin.links.from_hours_ago(params[:time])
    else
      bin.links.since(params[:since])
    end
  end
  expose(:latest_links) { Link.nonprivate.latest }

  def index
    if bin.nil?
      flash[:error] = "That bin does not exist"
      redirect_to root_path
    else
      respond_to do |wants|
        wants.html
        wants.xml { render action: 'index', layout: false }
        wants.json { render json: links }
      end
    end
  end

  def create
    link.touch unless link.new_record?
    if link.save
      if request.xhr?
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Request-Method'] = 'POST, OPTIONS'
        render text: '', status: 200
      else
        flash[:success] = "Link Added"
        redirect_to bin_links_path link.bin.secret_hash
      end
    else
      flash[:error] = "Unable to add link"
      if bin.present?
        render 'index'
      else
        render new_bin_path
      end
    end
  end

  def latest

  end

  def destroy
    link = bin.links.find(params[:id])
    link.destroy
    respond_to do |wants|
      wants.html do
        flash[:success] = "Link deleted"
        redirect_to bin_links_path(bin)
      end
      wants.json { render json: link }
    end
  end

  def bookmarklet
    render 'bins/_bookmarklet_response'
  end

  def cross_site_sharing
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = 'POST, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With'
    headers['Access-Control-Max-Age'] = '1278000'
    headers['Content-Length'] = '0'
    headers['Content-Type'] = 'text/plain'
    render nothing: true, status: 200
  end

  def title
    if bin
      "#{bin.title} Bin"
    else
      "Latest"
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  expose(:domains) { Domain.top }

  def title
    "Stats"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bins_helper.rb
module BinsHelper
  def class_for_time_selection(time)
    time == ( params[:time] || '24') ? 'current_view' : ''
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bins/_bookmarklet.html.haml
- post_location = bookmarklet_url(bin)
- marklet = h(                                                                  |
  "javascript:function bsv(){var d=document,"+                                  |
  "z=d.createElement('scr'+'ipt'),b=d.body,"+                                   |
  "l=d.location;try{if(!b)throw(0);"+                                           |
  "z.setAttribute('src',"+                                                      |
  "'#{post_location}');"+                                                       |
  "b.appendChild(z);}catch(e){alert('Wait for page to load!');}}bsv();void(0)") |
= link_to "Bookmarklet", marklet

- if ::Rails.env.test?
  - post_location += '?allow_same_domain=true'
  - marklet = h(                                                                  |
    "javascript:function bsv(){var d=document,"+                                  |
    "z=d.createElement('scr'+'ipt'),b=d.body,"+                                   |
    "l=d.location;try{if(!b)throw(0);"+                                           |
    "z.setAttribute('src',"+                                                      |
    "'#{post_location}');"+                                                       |
    "b.appendChild(z);}catch(e){alert('Wait for page to load!');}}bsv();void(0)") |
  = link_to "xBookmarklet-Same-Domain", marklet

app/views/bins/_bookmarklet_response.js.erb
var injectSaveDiv, req, saveDiv, sendRequest;
saveDiv = function() {
  var _div, _style;
  _style = 'background-color: #FFF;\ncolor: #000;\nfont-size: 24px;\ndisplay: block;\ntext-align: center;\npadding: 20px;\nposition: fixed;\ntop: 10px;\nleft: 10px;\nz-index: 999;\nborder:4px solid #000;';
  _div = document.createElement('div');
  _div.id = 'byus_link_saver';
  _div.innerHTML = "Link Saved <br/> To Bin";
  _div.setAttribute("style", _style);
  return _div;
};
removeSaveDiv = function() {
  var elem = document.getElementById('byus_link_saver');
  document.body.removeChild(elem);
}
injectSaveDiv = function() {
  var doc, loc;
  doc = document;
  doc.body.appendChild(saveDiv());
};
sendRequest = function() {
  req = new XMLHttpRequest();
  req.onreadystatechange = function() {
    if (req.readyState == 4 && (req.status == 200)) {
      injectSaveDiv();
      setTimeout(removeSaveDiv, 3000);
    }
  };
  req.open("POST", "<%=bin_links_url(bin)-%>", true);
  req.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
  req.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
  req.send("link[location]=" + document.location + "&link[title]=" + document.title);
}
<% if ::Rails.env.test? && params[:allow_same_domain] -%>
  sendRequest();
<%- else -%>
if( document.location.hostname == "<%= request.host %>" ) {
  $('#bookmarklet_helper').slideDown(1000);
} else {
  sendRequest();
};
<%- end %>

app/views/bins/edit.html.haml
= form_for bin do |f|
  = f.label :title, "Change Bin Title:"
  = f.text_field :title
  = f.submit "Change Title"

app/views/bins/new.html.haml
%h1.page_title
  Create a new bin
.new_link_form
  = form_for bin do |f|
    = f.fields_for :links, bin.links.build do |link|
      = link.label :location
      = link.text_field :location, {placeholder: "Enter a URL or Name", class: 'link_location'}
    = f.submit "Create", {class: 'link_submit'}
= error_messages_for bin, id: 'link_errors'
#service_info
  #getting_started
    %h2.subtitle
      Getting started:
    %ul
      %li Create a bin
      %li Bookmark your bin
      %li Add links
      %li Share
    %h2.subtitle
      Get Social:
    #twitter_follow
      = render 'shared/twitter_follow'
  #explanation
    %h2.subtitle
      Share links with friends
    %p
      Do you ever find yourself sending links to your friends through email,
      IMs, twitter, facebook, or other methods?
      Do you wish you could save time and just
      %em share links with a single click?
    %h3 Sharing is easy
    %p
      Make a bin (a place to hold links) and share either the public or private
      link with friends.
    %p
      Now you can share links with friends even if they're not available.
    %p
      No more sticky notes, emails, or other annoying reminders, just add the link to your bin
      and forget it!  Just make sure to come back once a day and check what your friends added!

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    %div{ :title => key.to_s.humanize, :class => key }
      %p= value

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}
  = link_to "Dave Lyon", 'http://davelyon.net/'
  %em.contact_me
    Bugs/Comments/Complaints:
    = mail_to 'isby@davelyon.net',"E-mail me"
%p
  Icons from:
  = link_to "Fam Fam Fam : Silk Icons", "http://www.famfamfam.com/lab/icons/silk/"
  and
  = link_to "Pixel-Mixer : Basic", "http://pixel-mixer.com/basic_set/"

- if ::Rails.env.development?
  = link_to "Last Bin", Bin.last

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title= "this.isby.us : #{controller.title}"
%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/
= yield :head
-# Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references
-# %link{ :rel => "shortcut icon", :href => "/favicon.ico" }/
-# %link{ :rel => "apple-touch-icon", :href => "/apple-touch-icon.png" }/

-# You can specify a stylesheet_partial when rendering this partial (i.e. admin/stylesheets)
- if local_assigns[:stylesheet_partial]
  = render :partial => local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects
= javascript_include_tag 'modernizr.min'

= csrf_meta_tag

app/views/layouts/_header.html.haml
%h1.site_title
  = link_to "this.isby.us", root_path
#tagline
  ad-hoc link sharing
  #header_navigation
    = link_to "home", root_path
    = link_to "latest", links_latest_path
    = link_to "stats", stats_path

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery, with a protocol relative URL
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
-# remote_jquery and local_jquery helpers use minified jquery unless Rails.env is development
- if !google_api_key.blank?
  = javascript_include_tag "//www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load(#{ remote_jquery("1.5.2") });
- else
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/#{ local_jquery("1.5.2") }"

-# fall back to local jQuery if necessary
:javascript
  window.jQuery || document.write("<script src='/javascripts/jquery.min.js'>\x3C/script>")
= javascript_include_tag 'rails', 'plugins', 'application', 'underscore-dev', 'backbone-dev', 'mustache'

-# Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb
/[if lt IE 7 ]
  = javascript_include_tag 'dd_belatedpng.js'
  :javascript
    //DD_belatedPNG.fix('img, .png_bg');
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
:javascript
  $('#flash').slideUp(3000).fadeOut(2000);

app/views/layouts/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'style', :media => 'all'
= stylesheet_link_tag 'header', :media => 'all'
= stylesheet_link_tag 'main', :media => 'all'
= stylesheet_link_tag 'bins', :media => 'all'
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"

  %body
    #container
      %header#header
        = render "layouts/header"

      #main{ :role => 'main' }
        = render "layouts/flashes"
        = yield

      %footer#footer
        = render "layouts/footer"

    -# Javascript at the bottom for fast page loading
    = render "layouts/javascripts"

app/views/links/_bin_help.html.haml
#bin_explanation
  .help#base_help
    = link_to "", "#closeHelp", { class: 'close' }
    %h3 What is a bin?
    %p
      %em A bin
      is a place to put links that you want to share with others.
      You may share either a public or private link to this bin that will allow others to see these links.
  .help#private_help{style: 'display: none'}
    = link_to "", "#closeHelp", { class: 'close'}
    %h3 What is a private link?
    %p
      The
      %em private link
      allows changes to be made by anyone at any time, so share it wiseley.
  .help#public_help{style: 'display: none'}
    = link_to "", "#closeHelp", { class: 'close'}
    %h3 What is a public link?
    %p
      The
      %em public link
      will allow people to see links that have been shared, but not make any changes or add any links.  You can share this with anyone safely.
  .help#bookmarklet_help{style: 'display: none'}
    = link_to "", "#closeHelp", { class: 'close'}
    %h3 What is a bookmarklet?
    %p
      The
      %em bookmarklet
      is a quick-save button for your bin.  Drag the bookmarklet to your bookmark bar in your browser, and you can click it from any page to have that page added to your bin.  You'll see a notification in the top left corner of the current page to indicate that it was saved.

app/views/links/_link.html.haml
- url = link.location
%li{ class: cycle('bin_link_dark','bin_link_light') }
  = link_to truncate(link.display_title, length: 60), url, {rel: 'nofollow'}
  - unless bin.nil?
    = link_to "[delete]", bin_link_path(bin.secret_hash,link.id), method: :delete, class: 'delete'

app/views/links/_listing.html.haml
#time_frame_selection
  Show links from the last:
  = link_to "24h", bin_links_path(bin,time: 24), {class: class_for_time_selection('24')}
  = link_to "48h", bin_links_path(bin,time: 48), {class: class_for_time_selection('48')}
  = link_to "1w" , bin_links_path(bin,time: 168), {class: class_for_time_selection('168')}
#link_list
  -if links.empty?
    .no_links
      No links have been added recently! Why don't you add one now? ;)
  -else
    %ul.links
      =render links

app/views/links/_model.js.erb
<% bin_url =  bin_links_path(bin.secret_hash) %>
$(document).ready( function() {
  var Link = Backbone.Model.extend({
    initialize: function(attributes) {
      var title = attributes.title;
      if(title.length > 60) {
        attributes.title = title.slice(0,57) + "...";
      }
      this.set(attributes);
    },
    url: function() { return "<%= bin_url %>/" + this.id}
  });

  var BinLinks = Backbone.Collection.extend({
    model: Link,
    initialize: function() {
      this.lastRequestTime = new Date().toUTCString();
    },
    url: function() {
      var url = "<%= bin_url %>";
      if ( this.timeRange ) { url = url + "?time=" + this.timeRange }
      return url;
    },
    latestUrl: function() {
      return "<%= bin_url %>" + "/?since=" + this.lastRequestTime;
    },
    comparator: function(link) { return -link.get('updated_at'); },
    add: function(added, options) {
      var self = this;
      _.each(added, function(link) {
        var existing = self.get(link.id);
        if(existing){
          existing.change();
        } else {
          Backbone.Collection.prototype.add.call(self, link, options);
        }
      });
    },
    getMore: function() {
      var links = this;
      $.ajax({
        url: this.latestUrl(),
        dataType: 'json',
        success: function(data, statusText, xhr) {
          if (data.length) {
            links.add(data);
            links.lastRequestTime = new Date().toUTCString();
          }
        },
        error: function(error) { console.log(error) }
      });
    },
    updateForTime: function(time) {
      this.timeRange = time;
      this.fetch({success: function() { console.log("New links!")}});
    }
  });

  var LinkView = Backbone.View.extend({
    tagName: "li",
    events: {
      "click .destroy": "delete"
    },
    initialize: function() {
      _.bindAll(this, 'render','updated');
      this.model.bind('change', this.updated);
      this.template = $("#link-template").html();
    },

    render: function() {
      $(this.el).html(Mustache.to_html(this.template, this.model.toJSON()));
      return this;
    },

    updated: function() {
      var self = this.el;
      $(this.el).fadeOut(1000, function() {
        $('#bin_links').find('.links').prepend(self);
        $(self).fadeIn(1000);
      });
    },

    delete: function() {
      var self = this;
      this.model.destroy({
        success: function() {
          $(self.el).fadeOut(1000, function() { self.remove() });
        },
        error: function() {
          console.log("Unable to delete at this time");
        }
      })
      return false;
    },
  });

  var BinLinksView = Backbone.View.extend({
    el: $('#bin_links'),

    events: { },

    initialize: function() {
      _.bindAll(this, 'addLink', 'addAll');

      Links.bind('add', this.addLink);
      Links.bind('refresh', this.addAll);

      Links.refresh(<%=raw links.to_json %>);
    },

    addLinkPlain: function(link) {
      var view = new LinkView({model: link});
      var renderedView = view.render().el;
      $('.links').prepend(renderedView);
      return renderedView;
    },

    addLink: function(link) {
      $(this.addLinkPlain(link)).hide().fadeIn(1000);
    },

    addAll: function() {
      $(this.el).find('.links').empty();
      if(Links.length == 0){
        $('.links').html("<p>No links have been added recently!</p>");
      } else {
        Links.each(this.addLinkPlain);
      }
    }
  });

  var BinHelpView = Backbone.View.extend({
    el: $('#bin_controls'),

    events: {
      "click #info_secret"      : "showSecret",
      "click #info_public"      : "showPublic",
      "click #info_bookmarklet" : "showBookmarklet",
      "click .close"            : "closeHelp"
    },

    hideAll: function() { $('.help').hide() },

    showSecret: function() {
      this.hideAll();
      $("#private_help").toggle();
    },

    showPublic: function() {
      this.hideAll();
      $("#public_help").toggle();
    },

    showBookmarklet: function() {
      this.hideAll();
      $("#bookmarklet_help").toggle();
    },

    closeHelp: function() {
      this.hideAll();
    }
  });

  var BinController = Backbone.Controller.extend({

    routes: {
      "links/:time" : "updateForTime"
    },

    updateForTime: function(time) {
      Links.updateForTime(time);
      $('#time_frame_selection').find('a').removeClass('current_view');
      $('#time_frame_selection').find('.'+time).addClass('current_view');
    }

  });


  window.Links = new BinLinks;
  window.App = new BinLinksView;
  window.Controller = new BinController;
  window.HelpView = new BinHelpView;
  Backbone.history.start();
  setInterval( 'Links.getMore()', 30000);
});

app/views/links/index.html.haml
- content_for :head do
  %link{rel: 'alternate', type: 'application/rss+xml', href: "#{bin_links_url(bin, format: 'xml')}"}
#bookmarklet_helper
  %p
    = image_tag("up_48.png")
    Drag
    = render 'bins/bookmarklet'
    here
    = link_to image_tag("cross.png"), "javascript:$('#bookmarklet_helper').slideUp(1000);"
    = image_tag("up_48.png")
%h1.page_title
  = "#{bin.title} Bin"
  = link_to image_tag("feed-small.png"), bin_links_path(bin,format: 'xml')
  %span.public= bin.public_status.capitalize
#bin_controls
  #bin_access_links
    %ul.bin_access
      %li
        = link_to "Private Link",bin_url(bin.secret_hash)
        = image_tag("information.png", {id: 'info_secret'})
        %li
          = link_to_if bin.allow_public?, "Public Link", public_bin_links_path(bin.public_hash) do
            Bin is Private
          = image_tag("information.png", {id: 'info_public'})
      %li
        = render 'bins/bookmarklet'
        = image_tag("information.png", {id: 'info_bookmarklet'})
      %li
        = link_to "Rename Bin", edit_bin_path(bin)
      - if bin.allow_public?
        %li= link_to "Make this bin private", bin_path(bin, bin: { allow_public:false } ), method: :put
      - else
        %li= link_to "Make this bin public",bin_path(bin, bin: { allow_public:true } ), method: :put
      %li= link_to "RSS Feed", bin_links_path(bin, format: 'xml')
  = render :partial => 'bin_help'
.new_link_form
  = form_for [bin,link] do |f|
    #link_fields
      = f.label :location
      = f.url_field :location, {placeholder: "Enter a URL", class: 'link_location'}
      = f.submit "Add", {class: 'link_submit'}
= error_messages_for link, id: 'link_errors'
#bin_links
  #time_frame_selection
    Show links from the last:
    = link_to "24h", "#links/24", { class: '24' }
    = link_to "48h", "#links/48", { class: '48' }
    = link_to "1w", "#links/168", { class: '168'}
  %ul.links
%script#link-template{type: "text/template"}
  %a{href: "{{ location }}" }
    {{ title }}
  %a{href: '#', class: 'destroy'} Delete
- content_for :javascripts do
  %script
    = render 'model.js'

app/views/links/latest.html.haml
%h1.page_title Latest Links
#link_list
  %ul.links= render latest_links

app/views/shared/_twitter_follow.html.haml
<a href="http://twitter.com/thisisbyus" class="twitter-follow-button" data-show-count="false">Follow @thisisbyus</a>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

app/views/stats/index.html.haml
%h1.page_title
  this.isby.us Statistics

%h2.subtitle
  Most Submitted Domains
- unless domains.empty?
  %ul#domains.links
    - domains.each do |domain|
      %li{ class: cycle('bin_link_dark', 'bin_link_light') }
        = "#{domain.root} (#{domain.links_count})"